# Generated by Django 5.0.4 on 2024-04-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_articulos_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad_total_articulos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
