# Generated by Django 5.0.4 on 2024-04-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_articulos_pedidos', '0002_pedido_cantidad_total_articulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad_total_articulos',
        ),
    ]
