# Generated by Django 5.0.4 on 2024-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_articulos_pedidos', '0003_remove_pedido_cantidad_total_articulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad_articulos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
