# Generated by Django 5.0.4 on 2024-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_articulos_pedidos', '0005_alter_pedido_precio_total_con_impuestos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='articulos',
        ),
        migrations.AlterField(
            model_name='articulopedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
