# Generated by Django 5.0.4 on 2024-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_articulos_pedidos', '0006_remove_pedido_articulos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='articulos',
            field=models.ManyToManyField(through='gestion_articulos_pedidos.ArticuloPedido', to='gestion_articulos_pedidos.articulo'),
        ),
        migrations.AlterField(
            model_name='articulopedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
